"""Added ErrorReport.

Revision ID: 17f9b17a63ce
Revises: 655529cd9ea2
Create Date: 2016-04-29 13:48:14.433707

"""

# revision identifiers, used by Alembic.
revision = '17f9b17a63ce'
down_revision = '655529cd9ea2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('stacktrace', sa.String(), nullable=True),
    sa.Column('route', sa.String(length=75), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('error_report')
    ### end Alembic commands ###
