"""Invitation.status

Revision ID: 655529cd9ea2
Revises: 87210e84414a
Create Date: 2016-04-21 06:28:58.221855

"""

# revision identifiers, used by Alembic.
revision = '655529cd9ea2'
down_revision = '87210e84414a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitation', sa.Column('status', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitation', 'status')
    ### end Alembic commands ###
