"""empty message

Revision ID: 8017298d17f5
Revises: 17f9b17a63ce
Create Date: 2016-05-04 06:36:26.880313

"""

# revision identifiers, used by Alembic.
revision = '8017298d17f5'
down_revision = '17f9b17a63ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_invitation', sa.Integer(), nullable=True),
    sa.Column('meeting_date', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_invitation'], ['invitation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consult_attendees',
    sa.Column('consult_id', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consult_id'], ['consult.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], )
    )
    op.add_column('attendees', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.drop_constraint('attendees_profile.id_fkey', 'attendees', type_='foreignkey')
    op.create_foreign_key(None, 'attendees', 'profile', ['profile_id'], ['id'])
    op.drop_column('attendees', 'profile.id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendees', sa.Column('profile.id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'attendees', type_='foreignkey')
    op.create_foreign_key('attendees_profile.id_fkey', 'attendees', 'profile', ['profile.id'], ['id'])
    op.drop_column('attendees', 'profile_id')
    op.drop_table('consult_attendees')
    op.drop_table('consult')
    ### end Alembic commands ###
