"""Invitation meeting date

Revision ID: 87210e84414a
Revises: 89109dd8dbf0
Create Date: 2016-04-20 21:21:17.725935

"""

# revision identifiers, used by Alembic.
revision = '87210e84414a'
down_revision = '89109dd8dbf0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitation', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('invitation', sa.Column('meeting_date', sa.DateTime(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitation', 'meeting_date')
    op.drop_column('invitation', 'duration')
    ### end Alembic commands ###
