"""empty message

Revision ID: 89109dd8dbf0
Revises: None
Create Date: 2016-04-20 06:39:39.428568

"""

# revision identifiers, used by Alembic.
revision = '89109dd8dbf0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userid')
    )
    op.create_table('invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendees',
    sa.Column('invitation_id', sa.Integer(), nullable=True),
    sa.Column('profile.id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitation.id'], ),
    sa.ForeignKeyConstraint(['profile.id'], ['profile.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendees')
    op.drop_table('invitation')
    op.drop_table('profile')
    ### end Alembic commands ###
